### ISSUE TITLE
报错please select method or class

### ISSUE THREAD

**Issue by xuhuan** [FurionCS/YapiIdeaUploadPlugin#8]
不管选择类还是方法均提示
```
please select method or class
```
错误提示如下：
```
java.lang.NullPointerException
	at com.qbb.interaction.UploadToYapi.actionPerformed(UploadToYapi.java:112)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:616)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:665)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:664)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:512)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:217)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:665)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by FurionCS** [comment]
请告知下，idea 版本

**Comment by xuhuan** [comment]
> 请告知下，idea 版本

2019.1

**Comment by pollux0508** [comment]
已验证，请核对下misc.xml中的projectId和token

**Comment by xuhuan** [comment]
> 已验证，请核对下misc.xml中的projectId和token，我也是出现这种问题，经过多测查看确定是token和projectId对应不上 

确认过多次这2个值，是对的，token是直接粘贴的，并通过搜索进行了比对。id也是对的，我是Maven多模块的项目。

**Comment by FurionCS** [comment]
请加我qq 1115206778

**Comment by xuhuan** [comment]
> 请加我qq 1115206778

请求已发，联系方式如果是非公开的话建议可以私信，防止信息泄露。

**Comment by FurionCS** [comment]
选择方法名称上传，而不是光标在方法上
